(()=>{
'use strict';
const CFG={lat:-23.4347,lon:-45.0711,marineLat:-23.5,marineLon:-44.25,tz:'America/Sao_Paulo',forecastDays:7,refreshMs:30*60*1000,staleMs:15*60*1000};
const $=id=>document.getElementById(id);
const dirs=['N','NE','L','SE','S','SO','O','NO'];
const state={marine:null,wind:null,tides:null,selectedDay:'',latest:null,lastLoad:0,sourceMode:'primary',currentSpotId:localStorage.getItem('code_current_spot')||'',editingSpotId:null,map:null,mapMarker:null,pendingPoint:null};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const fmt=(n,d=1)=>Number.isFinite(Number(n))?Number(n).toFixed(d):'—';
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
const dir=d=>Number.isFinite(Number(d))?dirs[Math.round((((Number(d)%360)+360)%360)/45)%8]:'—';
const localDate=ts=>new Date(ts+':00-03:00');
const dayPlus=(day,n)=>{const d=new Date(day+'T12:00:00-03:00');d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)};
const dayName=(day,long=false)=>new Intl.DateTimeFormat('pt-BR',long?{weekday:'long',day:'2-digit',month:'2-digit'}:{weekday:'short'}).format(new Date(day+'T12:00:00-03:00')).replace('.','');
const storage={sessions:()=>{try{return JSON.parse(localStorage.getItem('code_sessions')||'[]')}catch{return[]}},setSessions:v=>localStorage.setItem('code_sessions',JSON.stringify(v)),spots:()=>{try{return JSON.parse(localStorage.getItem('code_spots')||'[]')}catch{return[]}},setSpots:v=>localStorage.setItem('code_spots',JSON.stringify(v)),alerts:()=>{try{return JSON.parse(localStorage.getItem('code_alert_settings')||'{"enabled":true,"lead":12,"spots":{}}')}catch{return{enabled:true,lead:12,spots:{}}}},setAlerts:v=>localStorage.setItem('code_alert_settings',JSON.stringify(v))};
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);
function nearestIndex(times,target=Date.now()){let best=0,delta=Infinity;times.forEach((v,i)=>{const d=Math.abs(localDate(v).getTime()-target);if(d<delta){delta=d;best=i}});return best}
function nearestInDay(times,day,targetHour=12){let idx=-1,delta=Infinity;times.forEach((v,i)=>{if(!v.startsWith(day))return;const h=Number(v.slice(11,13))+Number(v.slice(14,16))/60,d=Math.abs(h-targetHour);if(d<delta){delta=d;idx=i}});return idx}
function energy(H){H=Number(H);return Number.isFinite(H)?1025*9.81*H*H/16:null}
function windIndex(ts){if(!state.wind?.hourly?.time?.length)return 0;const exact=state.wind.hourly.time.indexOf(ts);return exact>=0?exact:nearestIndex(state.wind.hourly.time,localDate(ts).getTime())}
function periodAt(i){const h=state.marine?.hourly||{};const total=Number(h.wave_period?.[i]);if(Number.isFinite(total)&&total>0)return total;const vals=[h.swell_wave_period?.[i]].map(Number).filter(v=>Number.isFinite(v)&&v>0);return vals.length?Math.max(...vals):null}
function offshore(d){d=((Number(d)%360)+360)%360;return Number.isFinite(d)&&d>=225&&d<=315}
function onshore(d){d=((Number(d)%360)+360)%360;return Number.isFinite(d)&&d>=45&&d<=135}
function quality(kind,val,dirDeg=null){const n=Number(val);if(!Number.isFinite(n))return null;let good=false,intensity=.3,label='';if(kind==='wave'){good=n>=1.8;intensity=good?clamp((n-1.8)/1.0,.2,1):clamp((1.8-n)/1.25,.2,1);label=good?'SWELL FORTE':'SWELL BAIXO'}else if(kind==='period'){good=n>=10;intensity=good?clamp((n-10)/6,.2,1):clamp((10-n)/4,.2,1);label=good?'PERÍODO BOM':'PERÍODO CURTO'}else if(kind==='wind'){const d=Number(dirDeg),light=n<=5,terral=offshore(d);good=light||terral;if(good){intensity=terral?Math.max(.35,clamp(n/15,.25,.85)):.25;label=light?'VENTO LEVE':'TERRAL'}else{intensity=clamp((n-5)/13,.25,1);label=onshore(d)?'MARAL':'VENTO FORTE'}}else return null;const light=good?[207,242,218]:[250,222,223],dark=good?[18,101,59]:[124,36,46],mix=(a,b,t)=>Math.round(a+(b-a)*t),bg=`rgb(${mix(light[0],dark[0],intensity)} ${mix(light[1],dark[1],intensity)} ${mix(light[2],dark[2],intensity)})`;return{good,intensity,label,bg,dark:intensity>.55}}
function qStyle(kind,val,dirDeg=null){const q=quality(kind,val,dirDeg);return q?`background:${q.bg};color:${q.dark?'#f7fff8':'#08150d'};font-weight:800`:''}
function overallQuality(wave,period,wind,windDir){const scores=[quality('wave',wave)?.good,quality('period',period)?.good,quality('wind',wind,windDir)?.good].filter(v=>v!==undefined);const n=scores.filter(Boolean).length;if(n===3)return{cls:'good',text:'BOAS CONDIÇÕES'};if(n<=1)return{cls:'bad',text:'CONDIÇÕES FRACAS'};return{cls:'mixed',text:'CONDIÇÕES MISTAS'}}
function ratingCount(wave,period,wind,windDir){return[quality('wave',wave)?.good,quality('period',period)?.good,quality('wind',wind,windDir)?.good].filter(Boolean).length}
async function fetchJSON(url,timeout=12000){const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),timeout);try{const r=await fetch(url,{cache:'no-store',signal:ctl.signal});if(!r.ok)throw new Error('HTTP '+r.status);return await r.json()}finally{clearTimeout(timer)}}
function marineURL(fallback=false){const p=new URLSearchParams({latitude:CFG.marineLat,longitude:CFG.marineLon,hourly:'wave_height,wave_direction,wave_period,swell_wave_height,swell_wave_direction,swell_wave_period',timezone:CFG.tz,forecast_days:CFG.forecastDays,cell_selection:'sea'});if(!fallback)p.set('models','ncep_gfswave025');return'https://marine-api.open-meteo.com/v1/marine?'+p}
function windURL(fallback=false){const p=new URLSearchParams({latitude:CFG.lat,longitude:CFG.lon,hourly:'wind_speed_10m,wind_direction_10m,wind_gusts_10m',wind_speed_unit:'kn',timezone:CFG.tz,forecast_days:CFG.forecastDays});if(!fallback)p.set('models','gfs_seamless');return'https://api.open-meteo.com/v1/forecast?'+p}
function cacheForecast(){if(!state.marine||!state.wind)return;localStorage.setItem('code_forecast_cache',JSON.stringify({saved:Date.now(),marine:state.marine,wind:state.wind}))}
function loadCachedForecast(){try{const c=JSON.parse(localStorage.getItem('code_forecast_cache')||'null');if(c?.marine?.hourly?.time?.length&&c?.wind?.hourly?.time?.length){state.marine=c.marine;state.wind=c.wind;state.sourceMode='cache';return c.saved||0}}catch{}return 0}
function setStatus(type,text){const el=$('status');if(!el)return;el.className='status '+(type||'');el.innerHTML=`<span class="dot"></span>${text}`}
async function loadForecast(force=false){if(!force&&state.lastLoad&&Date.now()-state.lastLoad<60000)return;setStatus('','sincronizando previsão…');let marine=null,wind=null,primary=true;try{[marine,wind]=await Promise.all([fetchJSON(marineURL(false)),fetchJSON(windURL(false))])}catch(err){console.warn('Primary forecast failed',err);primary=false;try{[marine,wind]=await Promise.all([fetchJSON(marineURL(true)),fetchJSON(windURL(true))])}catch(fallbackErr){console.warn('Fallback forecast failed',fallbackErr)}}try{state.tides=await fetchJSON('tides.json?v='+Date.now(),7000);localStorage.setItem('code_tides_cache',JSON.stringify(state.tides))}catch{try{state.tides=JSON.parse(localStorage.getItem('code_tides_cache')||'null')}catch{state.tides=null}}if(marine?.hourly?.time?.length&&wind?.hourly?.time?.length){state.marine=marine;state.wind=wind;state.sourceMode=primary?'primary':'fallback';state.lastLoad=Date.now();cacheForecast();const ix=nearestIndex(marine.hourly.time);const today=marine.hourly.time[ix].slice(0,10);if(!state.selectedDay||!marine.hourly.time.some(v=>v.startsWith(state.selectedDay)))state.selectedDay=today;renderForecast();setStatus('ok',`AO VIVO · atualizado ${new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}${primary?'':' · fonte alternativa'}`);return}const saved=loadCachedForecast();if(state.marine){const ix=nearestIndex(state.marine.hourly.time),today=state.marine.hourly.time[ix].slice(0,10);if(!state.selectedDay)state.selectedDay=today;renderForecast();setStatus('cache',`SEM CONEXÃO · exibindo última previsão salva${saved?' de '+new Date(saved).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'}):''}`)}else setStatus('err','PREVISÃO INDISPONÍVEL · toque em atualizar')}
function renderForecast(){renderDays();renderSelectedDay();renderRegisterCapture()}
function renderDays(){const h=state.marine?.hourly;if(!h)return;const by={};h.time.forEach((t,i)=>(by[t.slice(0,10)]??=[]).push(i));const today=h.time[nearestIndex(h.time)].slice(0,10);$('days').innerHTML=Object.entries(by).slice(0,7).map(([day])=>{const i=nearestInDay(h.time,day,12);if(i<0)return'';const ts=h.time[i],wi=windIndex(ts),wv=state.wind.hourly.wind_speed_10m[wi],wd=state.wind.hourly.wind_direction_10m[wi],wave=h.wave_height[i],p=periodAt(i),r=ratingCount(wave,p,wv,wd),label=day===today?'HOJE':dayName(day).toUpperCase();return`<button class="day-card ${day===state.selectedDay?'active':''}" data-day="${day}"><span class="day-name">${label}</span><span class="wave-glyph">≈</span><b>${fmt(wave)} m</b><div class="day-meta">${dir(h.wave_direction[i])} · ${fmt(p,0)}s</div><div class="rating-dots">${[1,2,3].map(x=>`<i class="${x<=r?'on':''}"></i>`).join('')}</div></button>`}).join('');$('days').querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>{state.selectedDay=b.dataset.day;renderSelectedDay();renderDays()})}
function selectedIndex(){const h=state.marine.hourly.time,today=h[nearestIndex(h)].slice(0,10);return state.selectedDay===today?nearestIndex(h):nearestInDay(h,state.selectedDay,12)}
function renderSelectedDay(){if(!state.marine||!state.wind)return;const i=selectedIndex();if(i<0)return;const h=state.marine.hourly,ts=h.time[i],wi=windIndex(ts),wave=Number(h.wave_height[i]),waveDir=Number(h.wave_direction[i]),p=periodAt(i),wind=Number(state.wind.hourly.wind_speed_10m[wi]),windDir=Number(state.wind.hourly.wind_direction_10m[wi]),gust=Number(state.wind.hourly.wind_gusts_10m[wi]),e=energy(wave),tide=tideValue(ts),today=h.time[nearestIndex(h.time)].slice(0,10),isToday=state.selectedDay===today,overall=overallQuality(wave,p,wind,windDir);state.latest={wave,waveDir,period:p,wind,windDir,gust,energy:e,tide,ts};$('selectedMoment').textContent=isToday?'HOJE · AGORA':dayName(state.selectedDay,true).toUpperCase()+' · 12H';$('selectedTitle').textContent=isToday?'Condições atuais':'Referência do dia';$('conditionPill').className='condition-pill '+overall.cls;$('conditionPill').textContent=overall.text;setMetric('waveCard','wave',fmt(wave)+' m',`${dir(waveDir)} · ${fmt(waveDir,0)}°`,'wave',wave);setMetric('periodCard','period',fmt(p,0)+' s','período dominante','period',p);setMetric('windCard','wind',fmt(wind,0)+' kt',`${dir(windDir)} · ${fmt(windDir,0)}° · ${quality('wind',wind,windDir)?.label||''}`,'wind',wind,windDir);setMetric('gustCard','gust',fmt(gust,0)+' kt','rajadas','wind',gust,windDir);$('energy').textContent=fmt(e,0);$('tideNow').textContent=Number.isFinite(Number(tide))?fmt(tide,2)+' m':'—';$('dayTitle').textContent=dayName(state.selectedDay,true);$('summarySource').textContent=state.sourceMode==='primary'?'GFS-Wave 0,25° + GFS':'fonte alternativa / cache';renderMatrix();drawTide();renderRegisterCapture()}
function setMetric(cardId,valueId,value,sub,kind,n,dirDeg=null){const card=$(cardId),v=$(valueId);v.textContent=value;card.querySelector('.metric-sub').textContent=sub;const q=quality(kind,n,dirDeg);if(q){card.style.background=q.bg;card.style.color=q.dark?'#f7fff8':'#07130d';card.querySelectorAll('small,.metric-sub,strong').forEach(el=>el.style.color='inherit')}}
function dayIndices(day){const times=state.marine.hourly.time;return times.map((t,i)=>[t,i]).filter(([t])=>{const hh=Number(t.slice(11,13));return t.startsWith(day)&&hh>=3&&hh<=23&&hh%2===1})}
function renderMatrix(){const rows=dayIndices(state.selectedDay);if(!rows.length){$('dayMatrix').innerHTML='<div class="empty">Sem dados para este dia.</div>';return}const H=state.marine.hourly,W=state.wind.hourly,head=rows.map(([t])=>`<th>${t.slice(11,13)}h</th>`).join('');const mk=(label,icon,valFn,styleFn)=>`<tr><td><span class="row-icon">${icon}</span>${label}</td>${rows.map(([t,i])=>`<td class="${styleFn?'quality-cell':''}"${styleFn?` style="${styleFn(t,i)}"`:''}>${valFn(t,i)}</td>`).join('')}</tr>`;let html=`<table class="forecast-table"><thead><tr><th>HORA</th>${head}</tr></thead><tbody>`;html+=mk('Ondulação','≈',(t,i)=>fmt(H.wave_height[i])+' m',(t,i)=>qStyle('wave',H.wave_height[i]));html+=mk('Dir. onda','↗',(t,i)=>dir(H.wave_direction[i])+' '+fmt(H.wave_direction[i],0)+'°');html+=mk('Período','◷',(t,i)=>fmt(periodAt(i),0)+' s',(t,i)=>qStyle('period',periodAt(i)));html+=mk('Vento','≋',(t,i)=>{const wi=windIndex(t);return fmt(W.wind_speed_10m[wi],0)+' kt'},(t,i)=>{const wi=windIndex(t);return qStyle('wind',W.wind_speed_10m[wi],W.wind_direction_10m[wi])});html+=mk('Rajadas','»',(t,i)=>{const wi=windIndex(t);return fmt(W.wind_gusts_10m[wi],0)+' kt'},(t,i)=>{const wi=windIndex(t);return qStyle('wind',W.wind_gusts_10m[wi],W.wind_direction_10m[wi])});html+=mk('Dir. vento','→',(t,i)=>{const wi=windIndex(t),d=W.wind_direction_10m[wi];return dir(d)+' '+fmt(d,0)+'°'});html+=mk('Energia','ϟ',(t,i)=>fmt(energy(H.wave_height[i]),0)+' J/m²');html+=mk('Maré','∿',(t,i)=>{const v=tideValue(t);return Number.isFinite(Number(v))?fmt(v,2)+' m':'—'});html+='</tbody></table>';$('dayMatrix').innerHTML=html}
function tideEvents(day){return state.tides?.events?.[day]||[]}
function tideEventMs(day,e){return new Date(`${day}T${e.time}:00-03:00`).getTime()}
function tideSeries(day){return[dayPlus(day,-1),day,dayPlus(day,1)].flatMap(d=>tideEvents(d).map(e=>({...e,day:d,ms:tideEventMs(d,e)}))).sort((a,b)=>a.ms-b.ms)}
function tideAtMs(ms,day){const a=tideSeries(day);if(!a.length)return null;let left=null,right=null;for(const e of a){if(e.ms<=ms)left=e;if(e.ms>=ms){right=e;break}}if(!left)return right?.height??null;if(!right)return left.height;if(left.ms===right.ms)return Number(left.height);const u=clamp((ms-left.ms)/(right.ms-left.ms)),ease=(1-Math.cos(Math.PI*u))/2;return Number(left.height)+(Number(right.height)-Number(left.height))*ease}
function tideValue(ts){if(!state.tides||!ts)return null;return tideAtMs(localDate(ts).getTime(),ts.slice(0,10))}
function drawTide(){const day=state.selectedDay,ev=tideEvents(day),svg=$('tideChart');$('tideDayLabel').textContent=dayName(day,true);if(!ev.length){svg.innerHTML='';$('tideRange').textContent='sem tábua para este dia';return}const start=new Date(`${day}T00:00:00-03:00`).getTime(),W=640,H=170,s=[];for(let i=0;i<=96;i++){const ms=start+i*15*60*1000,v=tideAtMs(ms,day);if(Number.isFinite(v))s.push([v,i/96*W])}const vals=s.map(x=>x[0]),min=Math.min(...vals),max=Math.max(...vals),pad=Math.max(.06,(max-min)*.12),lo=min-pad,hi=max+pad,y=v=>H-22-(v-lo)/(hi-lo)*(H-42),path=s.map(([v,x],i)=>(i?'L':'M')+x.toFixed(1)+','+y(v).toFixed(1)).join(' '),fill=path+` L ${W},${H-18} L 0,${H-18} Z`,marks=ev.map(e=>{const [hh,mm]=e.time.split(':').map(Number),x=(hh*60+mm)/1440*W,yy=y(Number(e.height)),dy=yy<48?17:-9;return`<circle cx="${x}" cy="${yy}" r="3" fill="#dffaff"/><text x="${x}" y="${yy+dy}" text-anchor="middle" font-size="8" fill="#a9bfca">${e.time} · ${fmt(e.height,2)}m</text>`}).join('');svg.innerHTML=`<path d="${fill}" fill="rgba(77,180,255,.10)"/><path d="${path}" fill="none" stroke="#66c7ff" stroke-width="2.2" vector-effect="non-scaling-stroke"/>${marks}`;$('tideRange').textContent=`${fmt(min,2)}–${fmt(max,2)} m`;$('tideSource').textContent=`${state.tides?.source||'tábua astronômica'} · alturas positivas no datum da tábua`}
function spotImage(i){const imgs=['https://images.unsplash.com/photo-1502680390469-be75c86b636f?auto=format&fit=crop&w=500&q=80','https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=500&q=80','https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?auto=format&fit=crop&w=500&q=80','https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&w=500&q=80'];return imgs[i%imgs.length]}
function confidenceFor(spot){const all=storage.sessions().filter(s=>s.spotId===spot.id),good=all.filter(s=>Number(s.score)>=8),base=spot.seed?12:0;return Math.min(95,base+good.length*12+all.length*2)}
function avgFor(spot){const a=storage.sessions().filter(s=>s.spotId===spot.id).map(s=>Number(s.score)).filter(Number.isFinite);return a.length?a.reduce((x,y)=>x+y,0)/a.length:null}
function renderSpots(){const list=$('spotsList'),spots=storage.spots(),sess=storage.sessions();list.innerHTML=spots.length?spots.map((s,i)=>{const avg=avgFor(s),conf=confidenceFor(s),count=sess.filter(x=>x.spotId===s.id).length;return`<div class="spot-card"><button class="spot-thumb" data-open="${s.id}" style="--spot-img:url('${spotImage(i)}')" aria-label="Abrir ${esc(s.name)}"></button><div class="spot-main" data-open="${s.id}"><b>${esc(s.name)}</b><small>${count} sessões${Number.isFinite(Number(s.lat))?' · ponto marcado':''}</small><div class="spot-rating"><span>${avg?stars(Math.round(avg/2)):'☆☆☆☆☆'}</span><span class="confidence-num">${conf}% confidence</span></div></div><div class="spot-actions"><button class="mini" data-edit="${s.id}">Editar</button><button class="mini danger" data-del="${s.id}">Excluir</button></div></div>`}).join(''):'<div class="empty">Nenhum pico cadastrado.<br>Crie o primeiro e marque o ponto no mapa.</div>';list.querySelectorAll('[data-open]').forEach(el=>el.onclick=()=>openSpot(el.dataset.open));list.querySelectorAll('[data-edit]').forEach(el=>el.onclick=()=>openSpotEditor(el.dataset.edit));list.querySelectorAll('[data-del]').forEach(el=>el.onclick=()=>deleteSpot(el.dataset.del));renderSpotSelect();renderAlerts()}
function stars(n){return'★★★★★'.split('').map((x,i)=>i<n?'★':'☆').join('')}
function renderSpotSelect(){const sel=$('spotSelect'),spots=storage.spots();if(!sel)return;sel.innerHTML=spots.length?spots.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join(''):'<option value="">Nenhum pico cadastrado</option>';sel.disabled=!spots.length;if(state.currentSpotId&&spots.some(s=>s.id===state.currentSpotId))sel.value=state.currentSpotId;$('noSpot').classList.toggle('hidden',!!spots.length);$('saveSession').disabled=!spots.length;$('saveSession').style.opacity=spots.length?'1':'.45'}
function openSpot(id){state.currentSpotId=id;localStorage.setItem('code_current_spot',id);renderSpotDetail();location.hash='spot'}
function learnedRange(arr,key,d=1,u=''){const v=arr.map(x=>Number(x[key])).filter(Number.isFinite);return v.length?`${Math.min(...v).toFixed(d)}–${Math.max(...v).toFixed(d)}${u}`:'Dados insuficientes'}
function renderSpotDetail(){const spot=storage.spots().find(s=>s.id===state.currentSpotId);if(!spot){$('spotTitle').textContent='PICO';return}const all=storage.sessions().filter(s=>s.spotId===spot.id),good=all.filter(s=>Number(s.score)>=8),conf=confidenceFor(spot),avg=avgFor(spot),seed=spot.seed||null;$('spotTitle').textContent=spot.name.toUpperCase().slice(0,20);$('spotScore').textContent=avg?avg.toFixed(1):'—';$('spotStars').textContent=avg?stars(Math.round(avg/2)):'☆☆☆☆☆';$('spotSessionCount').textContent=all.length+' sessões';$('spotConf').textContent=conf+'%';$('confBar').style.width=conf+'%';$('codeOrigin').textContent=good.length?`Confirmado por ${good.length} sessão(ões) boas${seed?' · norte inicial ainda ponderado':''}`:seed?'Norte inicial · baixa confiança':'Sem norte inicial cadastrado.';if(good.length){$('learnWave').textContent=learnedRange(good,'wave',1,' m');$('learnPeriod').textContent=learnedRange(good,'period',0,' s');$('learnWind').textContent=learnedRange(good,'wind',0,' kt');$('learnEnergy').textContent=learnedRange(good,'energy',0,' J/m²')}else if(seed){const rr=(a,b,u='')=>a!=null||b!=null?`${a??'—'}${b!=null?'–'+b:''}${u}`:'Dados insuficientes';$('learnWave').textContent=rr(seed.waveMin,seed.waveMax,' m')+(seed.swellDir?' · '+esc(seed.swellDir):'');$('learnPeriod').textContent=rr(seed.periodMin,seed.periodMax,' s');$('learnWind').textContent=(seed.windDir||'—')+(seed.windMax!=null?' · até '+seed.windMax+' kt':'');$('learnEnergy').textContent='Aprendendo pelas sessões'}else['learnWave','learnPeriod','learnWind','learnEnergy'].forEach(id=>$(id).textContent='Dados insuficientes');$('history').innerHTML=all.length?all.slice().reverse().map(s=>`<div class="history-item"><b>${esc(s.date)} · ${s.score}/10</b><small>${fmt(s.wave)} m · ${dir(s.waveDir)} ${fmt(s.waveDir,0)}° · ${fmt(s.period,0)} s · ${dir(s.windDir)} ${fmt(s.wind,0)} kt</small>${s.size||s.comment?`<small>${esc(s.size||'')}${s.comment?' · '+esc(s.comment):''}</small>`:''}</div>`).join(''):'<small>Nenhuma sessão registrada.</small>';$('overviewBest').innerHTML=`<div class="row"><span>Ondulação</span><b>${$('learnWave').textContent}</b></div><div class="row"><span>Período</span><b>${$('learnPeriod').textContent}</b></div><div class="row"><span>Vento</span><b>${$('learnWind').textContent}</b></div>`}
function showSpotTab(name){document.querySelectorAll('.spot-tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));document.querySelectorAll('.spot-panel').forEach(p=>p.classList.toggle('active',p.dataset.panel===name))}
function openSpotEditor(id=null){state.editingSpotId=id;const spot=storage.spots().find(s=>s.id===id),seed=spot?.seed||{};$('modalTitle').textContent=spot?'Editar pico':'Novo pico';$('spotName').value=spot?.name||'';$('spotLat').value=spot?.lat??'';$('spotLon').value=spot?.lon??'';$('seedWaveMin').value=seed.waveMin??'';$('seedWaveMax').value=seed.waveMax??'';$('seedPeriodMin').value=seed.periodMin??'';$('seedPeriodMax').value=seed.periodMax??'';$('seedSwellDir').value=seed.swellDir??'';$('seedWindDir').value=seed.windDir??'';$('seedWindMax').value=seed.windMax??'';$('seedNote').value=seed.note??'';updateLocationSummary();$('spotModal').classList.add('show');setTimeout(()=>$('spotName').focus(),50)}
function closeSpotEditor(){$('spotModal').classList.remove('show');state.editingSpotId=null}
function numField(id){const v=$(id).value.trim().replace(',','.');return v===''?null:Number(v)}
function saveSpot(){const name=$('spotName').value.trim();if(!name)return alert('Dê um nome ao pico.');const lat=numField('spotLat'),lon=numField('spotLon'),seed={waveMin:numField('seedWaveMin'),waveMax:numField('seedWaveMax'),periodMin:numField('seedPeriodMin'),periodMax:numField('seedPeriodMax'),swellDir:$('seedSwellDir').value.trim(),windDir:$('seedWindDir').value.trim(),windMax:numField('seedWindMax'),note:$('seedNote').value.trim()},hasSeed=Object.values(seed).some(v=>v!==null&&v!=='');const spots=storage.spots();if(state.editingSpotId){const s=spots.find(x=>x.id===state.editingSpotId);if(s){s.name=name;s.lat=lat;s.lon=lon;s.seed=hasSeed?seed:null}}else{const id=uid();spots.push({id,name,lat,lon,seed:hasSeed?seed:null});state.currentSpotId=id;localStorage.setItem('code_current_spot',id)}storage.setSpots(spots);closeSpotEditor();renderSpots();renderSpotDetail()}
function deleteSpot(id){const spots=storage.spots(),spot=spots.find(s=>s.id===id);if(!spot)return;if(!confirm(`Excluir ${spot.name} e o histórico desse pico?`))return;storage.setSpots(spots.filter(s=>s.id!==id));storage.setSessions(storage.sessions().filter(s=>s.spotId!==id));if(state.currentSpotId===id){state.currentSpotId='';localStorage.removeItem('code_current_spot')}renderSpots();renderSpotDetail()}
function updateLocationSummary(){const lat=$('spotLat').value,lon=$('spotLon').value,ok=lat!==''&&lon!=='';$('spotLocationSummary').classList.toggle('marked',ok);$('spotLocationSummary').textContent=ok?`Ponto marcado · ${Number(lat).toFixed(5)}, ${Number(lon).toFixed(5)}`:'Nenhum local marcado'}
function openMap(){const lat=Number($('spotLat').value),lon=Number($('spotLon').value),has=$('spotLat').value!==''&&$('spotLon').value!==''&&Number.isFinite(lat)&&Number.isFinite(lon);state.pendingPoint=has?{lat,lon}:null;$('mapResults').innerHTML='';$('mapSearch').value='';$('mapModal').classList.add('show');setTimeout(()=>{if(!window.L){$('mapCoords').textContent='Mapa indisponível. Tente novamente em alguns segundos.';return}if(!state.map){state.map=L.map('mapCanvas',{zoomControl:true}).setView(has?[lat,lon]:[CFG.lat,CFG.lon],has?16:11);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(state.map);state.map.on('click',e=>setMapPoint(e.latlng.lat,e.latlng.lng,'Ponto marcado'))}else{state.map.invalidateSize();state.map.setView(has?[lat,lon]:[CFG.lat,CFG.lon],has?16:11)}if(has)setMapPoint(lat,lon,'Ponto atual');else{$('mapCoords').textContent='Busque uma praia ou toque no mapa para marcar o pico.';if(state.mapMarker){state.map.removeLayer(state.mapMarker);state.mapMarker=null}}},120)}
function closeMap(){$('mapModal').classList.remove('show')}
function setMapPoint(lat,lon,label='Ponto marcado'){lat=Number(lat);lon=Number(lon);if(!Number.isFinite(lat)||!Number.isFinite(lon))return;state.pendingPoint={lat,lon};if(state.map){if(!state.mapMarker)state.mapMarker=L.marker([lat,lon]).addTo(state.map);else state.mapMarker.setLatLng([lat,lon]);state.map.panTo([lat,lon])}$('mapCoords').textContent=`${label} · ${lat.toFixed(6)}, ${lon.toFixed(6)}`}
async function searchMap(){const q=$('mapSearch').value.trim();if(!q)return;$('mapSearchBtn').textContent='…';$('mapResults').innerHTML='<div class="hintbox">Buscando…</div>';try{const data=await fetchJSON('https://nominatim.openstreetmap.org/search?format=jsonv2&limit=5&accept-language=pt-BR&countrycodes=br&q='+encodeURIComponent(q),10000);if(!data.length){$('mapResults').innerHTML='<div class="hintbox">Nenhum resultado. Tente incluir Ubatuba ou o nome da praia.</div>';return}$('mapResults').innerHTML=data.map((x,i)=>`<button class="map-result" data-map-result="${i}" type="button">${esc(x.display_name)}</button>`).join('');$('mapResults').querySelectorAll('[data-map-result]').forEach(b=>b.onclick=()=>{const x=data[Number(b.dataset.mapResult)],lat=Number(x.lat),lon=Number(x.lon);setMapPoint(lat,lon,x.display_name.split(',').slice(0,2).join(','));state.map.setView([lat,lon],16);$('mapResults').innerHTML=''})}catch{$('mapResults').innerHTML='<div class="hintbox">Não consegui buscar agora. Você ainda pode navegar e tocar diretamente no mapa.</div>'}finally{$('mapSearchBtn').textContent='BUSCAR'}}
function renderRegisterCapture(){if(!state.latest)return;const x=state.latest;$('rs').textContent=`${fmt(x.wave)} m · ${dir(x.waveDir)} ${fmt(x.waveDir,0)}°`;$('rp').textContent=fmt(x.period,0)+' s';$('rw').textContent=`${dir(x.windDir)} ${fmt(x.wind,0)} kt · raj. ${fmt(x.gust,0)}`;$('re').textContent=fmt(x.energy,0)+' J/m²';$('rt').textContent=Number.isFinite(Number(x.tide))?fmt(x.tide,2)+' m':'—'}
function saveSession(){const spots=storage.spots(),spotId=$('spotSelect').value,spot=spots.find(s=>s.id===spotId),score=document.querySelector('input[name="score"]:checked');if(!spot)return alert('Crie um pico antes de registrar a sessão.');if(!state.latest)return alert('A previsão ainda não carregou.');if(!score)return alert('Escolha uma nota de 6 a 10.');const arr=storage.sessions();arr.push({...state.latest,spotId,spotName:spot.name,score:Number(score.value),size:$('size').value.trim(),comment:$('comment').value.trim(),date:new Date().toLocaleDateString('pt-BR')});storage.setSessions(arr);state.currentSpotId=spotId;localStorage.setItem('code_current_spot',spotId);$('saved').style.display='block';renderSpots();renderSpotDetail();setTimeout(()=>{location.hash='spot';showSpotTab('overview');$('saved').style.display='none'},500)}
function renderAlerts(){const box=$('alertsList');if(!box)return;const spots=storage.spots(),cfg=storage.alerts();$('globalAlert').checked=cfg.enabled!==false;$('alertLead').value=String(cfg.lead||12);box.innerHTML=spots.length?spots.map(s=>`<div class="toggle-row"><div><b>${esc(s.name)}</b><small>monitorar aproximação do CODE</small></div><label class="switch"><input type="checkbox" data-alert-spot="${s.id}" ${cfg.spots?.[s.id]!==false?'checked':''}><span class="slider"></span></label></div>`).join(''):'<small>Nenhum pico cadastrado.</small>';box.querySelectorAll('[data-alert-spot]').forEach(el=>el.onchange=()=>{const x=storage.alerts();x.spots??={};x.spots[el.dataset.alertSpot]=el.checked;storage.setAlerts(x)})}
function bind(){$('refreshForecast').onclick=()=>loadForecast(true);$('addSpot').onclick=()=>openSpotEditor();$('cancelSpot').onclick=closeSpotEditor;$('saveSpot').onclick=saveSpot;$('spotModal').onclick=e=>{if(e.target===$('spotModal'))closeSpotEditor()};$('openMapPicker').onclick=openMap;$('cancelMap').onclick=closeMap;$('confirmMap').onclick=()=>{if(!state.pendingPoint)return alert('Marque um ponto no mapa primeiro.');$('spotLat').value=state.pendingPoint.lat.toFixed(6);$('spotLon').value=state.pendingPoint.lon.toFixed(6);updateLocationSummary();closeMap()};$('mapSearchBtn').onclick=searchMap;$('mapSearch').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();searchMap()}};$('mapModal').onclick=e=>{if(e.target===$('mapModal'))closeMap()};document.querySelectorAll('.spot-tab').forEach(b=>b.onclick=()=>showSpotTab(b.dataset.tab));$('saveSession').onclick=saveSession;$('globalAlert').onchange=()=>{const x=storage.alerts();x.enabled=$('globalAlert').checked;storage.setAlerts(x)};$('alertLead').onchange=()=>{const x=storage.alerts();x.lead=Number($('alertLead').value);storage.setAlerts(x)};window.addEventListener('hashchange',()=>{if(location.hash==='#spots'||location.hash==='#register'||location.hash==='#alerts')renderSpots();if(location.hash==='#spot')renderSpotDetail();if(location.hash==='#register')renderRegisterCapture()});document.addEventListener('visibilitychange',()=>{if(!document.hidden&&Date.now()-state.lastLoad>CFG.staleMs)loadForecast(true)})}
bind();renderSpots();renderSpotDetail();showSpotTab('overview');loadForecast(true);setInterval(()=>loadForecast(true),CFG.refreshMs);
})();